spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

logging.level.root=INFO

logging.level.com.example.business=DEBUG
logging.level.com.example.web=TRACE

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n
logging.file.name=logs/application.log
logging.file.max-size=10MB